hr/urls.py
from django.urls import path
from . import views

app_name = 'hr'

urlpatterns = [
	path('results/', views.JobSearchView.as_view(), name='results'),
	path('', views.HomePageView.as_view(), name='index'),

]

jimohhr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hr.urls', namespace='hr')),
]

hr/models.py
from django.db import models
from django.utils import timezone
# Create your models here.



class JobCategory(models.Model):
	category = models.CharField('category', max_length=200 )


	def __str__(self):
		return self.category


class Job(models.Model):
	job_title = models.CharField(max_length=200)
	job_image = models.FileField(upload_to='uploads/')
	job_description = models.TextField()
	job_keywords = models.CharField(max_length=400, null=True)
	job_location = models.CharField(max_length=400, null=True)
	job_category = models.ForeignKey(JobCategory, on_delete="models.CASCADE", null =True)
	job_duties = models.TextField()
	job_qualifications = models.TextField()
	published_date = models.DateTimeField(default=timezone.now())

	

	def __str__(self):
		return self.job_title

hr/forms.py
from django.forms import ModelForm
from .models import *

class SearchForm(ModelForm):
	class Meta:
		model = Job
		fields = ['job_keywords', 'job_location', 'job_category']

hr/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.views import generic, View
from .models import *
from .forms import *

# Create your views here.

class HomePageView(generic.ListView):
	model = JobCategory
	template_name = 'hr/index.html'
	context_object_name = 'job'

	def get_queryset(self): 
		return JobCategory.objects.all()



'''class MyFormView(View):
	form_class = MyForm
	initial = {'key':'value'}
	template_name = 'hr/results.html'

	def get(self, request, *args, **kwargs):
		form = self.form_class(initial=self.initial)
		return render(request, self.template_name, {'form':form})
'''
	





class JobSearchView(generic.ListView):
	model = Job
	template_name = 'hr/results.html'
	context_object_name = 'job_results'

	def get_queryset(request): 
		return Job.objects.filter(job_keywords=request.POST['keywords'], job_location=request.POST['location'], job_category=request.POST['item'])

hr/templates/hr/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hr/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'hr/font-awesome.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'hr/bootstrap.css' %}">
<head>
	


<title>JimohHr | Home </title>


<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Soft Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	
<script type="text/javascript">
	$(function(){
		$('#myCarousel').carousel();
	}

		);
</script>

	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--my js codes-->
	<a href="{% url 'hr:index' %}" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- js -->
	<script type="text/javascript" src="{% static 'hr/jquery-2.1.4.min.js' %}"></script>

	<script type="text/javascript" src="{% static 'hr/bootstrap.js' %}"></script>
</head>

<body>


	<link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">
	<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic'
	    rel='stylesheet' type='text/css'>

	   <div class="header" id="home">
		<div class="content white agile-info">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

					</div>
					<!--/.navbar-header-->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
							<ul class="nav navbar-nav">
								<li class="active"><a href="{% url 'hr:index' %}" class="effect-3">Home</a></li>
								
							</ul>
						</nav>
					</div>
					<!--/.navbar-collapse-->
					<!--/.navbar-->
				</div>
			</nav>
		</div>

	</div>



	<!--//banner -->


	<!--/search_form -->
	<div id="search_form" class="search_top">
		<h2>Start your job search</h2>
		<form action="{% url 'hr:results' %}" method="POST">
			{% csrf_token %}

			<input type="text" name="keywords" placeholder="Enter Keyword(s)" required="">
			<input class="email" name="location" type="text" placeholder="Location" required="">
			<select id="country12" onchange="change_country(this.value)" class="frm-field required">
														<option value="null"> Select Category</option>
														{% for item in job %}
														<option name="item" value="{{ item }}">{{ item }}</option>

														{% endfor %}
														
										</select>
			<input type="submit" value="FindJobs">
			<div class="clearfix"></div>
		</form>
	</div>
	<!--//search_form -->

<div class="banner-bottom">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">About Us</h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-6 banner_bottom_left">
					<h4>Employment opportunities for <span>Professionals</span></h4>
					<p>Pellentesque convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra pharetra sem, eget
						pulvinar neque pharetra ac.</p>
					<p>Lorem Ipsum convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra pharetra sem, eget
						pulvinar neque pharetra ac.</p>
					<ul class="some_agile_facts">
						<li><span class="fa fa-briefcase" aria-hidden="true"></span><label>80</label> Corporate Programs</li>
						<li><span class="fa fa-graduation-cap" aria-hidden="true"></span><label>49</label> Training Courses</li>
						<li><span class="fa fa-user" aria-hidden="true"></span><label>88</label> Strategic Partners</li>
						<li><span class="fa fa-line-chart" aria-hidden="true"></span><label>436</label> Companies We Helped</li>
					</ul>
					<div class="clearfix"> </div>
				</div>
				<div class="col-md-6 banner_bottom_right">
					<div class="agileits_w3layouts_banner_bottom_grid">
						<img src="images/ab.png" alt=" " class="img-responsive" />
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>

		</div>
	</div>
	<!-- //banner-bottom -->

<div class="team_work_agile">
		<h4>Whether we play a large or small role, by working together we achieve our objectives.</h4>
	</div>
	<!-- services -->
	<div class="services" id="services">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">Selection Process</h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-3 services-left">
					<div class="services-left-top">

						<h5>Identify Need & Develop Position Description</h5>

					</div>
					<div class="services-left-top services-left-top1">

						<h5>Recruitment Planning</h5>

					</div>
				</div>
				<div class="col-md-6 services-middle">
					<div class="services-middle-img">
						<img src="images/process.jpg" alt="" />
					</div>
					<div class="services-middle-grids">
						<div class="col-md-6 services-middle-left">
							<div class="services-left-top">

								<h5>Sourcing & Advertising</h5>

							</div>
						</div>
						<div class="col-md-6 services-middle-left">
							<div class="services-left-top">

								<h5>Assess & Interview Candidates</h5>

							</div>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="col-md-3 services-left">
					<div class="services-left-top">

						<h5>Offer for Student Employment</h5>

					</div>
					<div class="services-left-top services-left-top1">

						<h5>Onboarding for Success</h5>

					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //services -->
	<!-- /mid-services -->
	<div class="mid_services">

		<div class="col-md-6 according_inner_grids">
			<h3 class="agile_heading two">Receiving a Job offer</h3>
			<div class="according_info">
				<div class="panel-group about_panel" id="accordion" role="tablist" aria-multiselectable="true">
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingOne">
							<h4 class="panel-title asd">
								<a class="pa_italic" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true"
								    aria-controls="collapseOne">
							  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><i class="glyphicon glyphicon-minus" aria-hidden="true"></i>assumenda est cliche voluptate
							</a>
							</h4>
						</div>
						<div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
							<div class="panel-body panel_text">
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
								cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</div>
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingTwo">
							<h4 class="panel-title asd">
								<a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false"
								    aria-controls="collapseTwo">
							  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><i class="glyphicon glyphicon-minus" aria-hidden="true"></i>Itaque earum rerum
							</a>
							</h4>
						</div>
						<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
							<div class="panel-body panel_text">
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
								cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</div>
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingThree">
							<h4 class="panel-title asd">
								<a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false"
								    aria-controls="collapseThree">
							  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><i class="glyphicon glyphicon-minus" aria-hidden="true"></i>autem accusamus terry qui
							</a>
							</h4>
						</div>
						<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
							<div class="panel-body panel_text">
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
								cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</div>
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingThree">
							<h4 class="panel-title asd">
								<a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false"
								    aria-controls="collapseThree">
							  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><i class="glyphicon glyphicon-minus" aria-hidden="true"></i>autem accusamus terry qui
							</a>
							</h4>
						</div>
						<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
							<div class="panel-body panel_text">
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
								cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
		<div class="col-md-6 mid_services_img">
		</div>
		<div class="clearfix"> </div>
	</div>
	<!-- //mid-services -->
	<div class="candidate_cv">
		<div class="tittle_head_w3ls">
			<h3 class="tittle two">Candidate Cv</h3>
		</div>
		<div class="inner_sec_grids_info login-form">
			<form action="#" method="post">
				<div class="col-md-6 form-left">
					<div class="form-inputs email">
						<p>Full name</p>
						<i class="fa fa-user" aria-hidden="true"></i>
						<input type="text" name="Name" placeholder="" required="" />
					</div>
					<div class="form-inputs name">
						<p>Email</p>
						<i class="fa fa-envelope" aria-hidden="true"></i>
						<input type="email" name="Email" placeholder="" required="" />
					</div>
					<div class="form-inputs name">
						<p>Phone</p>
						<i class="fa fa-phone" aria-hidden="true"></i>
						<input type="text" name="Phone" placeholder="" required="" />
					</div>

				</div>
				<div class="col-md-6 form-right">
					<div class="form-inputs name">
						<p>Comment</p>
						<i class="fa fa-comment" aria-hidden="true"></i>
						<textarea name="Message" placeholder="" required=""></textarea>
					</div>
				</div>
				<div class="clearfix"></div>
				<div class="form-inputs">
					<p>Specify your current employment status</p>
					<ul>
						<li>
							<input type="radio" id="a-option" name="selector1">
							<label for="a-option">Employed </label>
							<div class="check"></div>
						</li>
						<li>
							<input type="radio" id="b-option" name="selector1">
							<label for="b-option">Unemployed</label>
							<div class="check"></div>
						</li>
						<li>
							<input type="radio" id="c-option" name="selector1">
							<label for="c-option">Self-Employed</label>
							<div class="check"></div>
						</li>
						<li>
							<input type="radio" id="d-option" name="selector1">
							<label for="d-option">Student</label>
							<div class="check"></div>
						</li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="form-inputs upload">
					<p>Upload your resume</p>
					<input type="file" id="fileselect" name="fileselect[]" multiple="multiple" />
					<div id="filedrag">Upload</div>
				</div>
				<input type="submit" value="Submit Cv">
			</form>

		</div>
	</div>
	<!-- //testimonials -->




	
</body>
















</body>

















	

hr/templates/hr/results.html
{% for result in job_results %}

<h1>{{ result }}</h1>

{% endfor %}